### ISSUE TITLE
Add support for rubygems-tasks

### ISSUE THREAD

**Issue by postmodern** [bkuhlmann/rubysmith#3]
## Overview

[rubygems-tasks](https://github.com/postmodern/rubygems-tasks#readme) are lightweight/modular rake tasks for building and publishing rubygems.

## Example

in the `.gemspec`:

```ruby
gem.add_development_dependency 'rubygems-tasks', '~> 0.2'
```

or in the `Gemfile`:

```ruby
gem 'rubygems-tasks', '~> 0.2'
```

`Rakefile`:

```ruby
require 'rubygems/tasks'
Gem::Tasks.new
```

**Comment by bkuhlmann** [comment]
Thanks. Yeah, I've looked at your project before. It's neat work but solves a similar but different problem than what Rubysmith is meant for. To explain, I have all of my projects fallback to using Bundler Rake tasks by default. Which is is fine. Where things get interesting is when it comes to publishing. There are two types of problems I've run into when publishing:

- **Projects**: These generally only require a Git tag. There is the whole issue of deployment but I'll skip that for now and only focus on tagging since that is the bare minimum.
- **Gems**: These need to be tagged and as well as deployed (i.e. pushed to RubyGems...or a private server).

In both of the above cases, this is solved by using [Milestoner](https://www.alchemists.io/projects/milestoner). In the situation in which I need to publish to RubyGems, I use [Gemsmith](https://www.alchemists.io/projects/gemsmith).

So what you are proposing here is more in line with Gemsmith, not Rubysmith. The distinction is Rubysmith is for Ruby projects only. If you want to craft and maintain gems, you'd use Gemsmith.

All of that said, we've sort of solved the same problem but in different ways. 😅 I'm currently rebuilding Gemsmith on top of Rubysmith and should have a major release out within the next week or two but I've moved away from Rake tasks since it causes a circular dependency which is hard to maintain over time. With the next major release of Gemsmith, everything will be CLI based so people don't have to require Rubysmith or Gemsmith within their own projects. I mean, they can, but at least they'll have the freedom to not have to to do that if they want.

---

I'm going to close this issue since it's beyond the scope of work for Rubysmith and more in the realm of Gemsmith. Feel free to continue the discussion if you like, though.
