### ISSUE TITLE
Add Minitest build option

### ISSUE THREAD

**Issue by dsisnero** [bkuhlmann/rubysmith#5]
## Overview
add a minitest and minitest spec option for testing

**Comment by bkuhlmann** [comment]
Hey dsisnero, thanks for the suggestion. :bow:

Do you have an idea of what support for minitest would look like and how involved it would be set up? Maybe some examples and best practices to point to in order evaluate the effort to incorporate and maintain? I guess I'd need some convincing since most people prefer RSpec. 😅

**Comment by bkuhlmann** [comment]
:information_source: Closing due to lack of feedback. I think there is some merit to this request but not so much as being part of Rubysmith core and more as an *extension* to Rubysmith. Allowing Rubysmith to be extended for drop-in customization behond what is provided in the core would be nice and something I've thought about for a while now but haven't been able to tackle and is probably the better solution, ultimately.
